### ISSUE TITLE
include gameplay rules

### ISSUE THREAD

**Issue by Danfro** [Arc676/Farkle-Linux#5]
it would be useful to include gameplay rules within the game so one can look them up rather than reading through the repo on github
Maybe they can be included under "about farkle"

**Comment by Arc676** [comment]
Closed for German with #7; translation of the rules in other languages not yet completed.

**Comment by Arc676** [comment]
Translations for the rest of the app are available in the following languages
[ ] Spanish
[ ] French
For consistency, translations should be added for gameplay rules in these languages too.

**Comment by Danfro** [comment]
If you do not get everything translated you could issue a new version. Maybe someone playing Farkle will help translating...

**Comment by Arc676** [comment]
I definitely intend to release a new version in the near future. I really want to get sound effects working in the next release though (#6).

**Comment by Danfro** [comment]
Of course that's great then, if you have some dev work going on. I just was curious if you only did not release a new version because you where waiting for those translations. :smirk: 

If it was just me, I always turn off sound effects. :smile: 
But I am sure lots of others are going to like it!
Although sound seems not to be an easy thing to get flawless working... Good luck!

**Comment by Arc676** [comment]
Closing this issue as the core issue has been addressed. Now tracking the Spanish translation's progress in #11.
